### ISSUE TITLE
Disable Etag not wrapped in <IfModule mod_headers.c>

### ISSUE THREAD

**Issue by Nucleoprotein** [JayHoltslander/jays-wp-htaccess#2]
As topic says. line 334 - disable Etag not wrapped in `<IfModule mod_headers.c>` and `Header` call cause internal server error if mod_headers is not loaded.

**Comment by JayHoltslander** [comment]
@Nucleoprotein Thanks for pointing that out. Strange that it never gave me an error in my usage. I've wrapped the lines. Closing.
